apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | default "" | quote }}
  NEXTAUTH_SECRET: {{ .Values.secrets.NEXTAUTH_SECRET | default "" | quote }}
  MONGO_USERNAME: {{ .Values.secrets.MONGO_USERNAME | default "" | quote }}
  MONGO_PASSWORD: {{ .Values.secrets.MONGO_PASSWORD | default "" | quote }}
