# Stage 1: Builder
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Install necessary build dependencies
RUN apk add --no-cache python3 make g++

# Copy package files and tsconfig
COPY package*.json tsconfig.json ./

# Copy scripts and data
COPY scripts ./scripts
COPY .db ./.db

# Install dependencies
RUN npm install
RUN npm install --save-dev @types/mongoose

# Set environment variables
ENV NODE_ENV=development

# Command to run migration
CMD ["npx", "ts-node", "--project", "scripts/tsconfig.json", "scripts/migrate-data.ts"]
